# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/elyass/Dungeon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/elyass/Dungeon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elyass/Dungeon/CMakeFiles /home/elyass/Dungeon//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elyass/Dungeon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/elyass/Dungeon/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Dungeon

# Build rule for target.
Dungeon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Dungeon
.PHONY : Dungeon

# fast build rule for target.
Dungeon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/build
.PHONY : Dungeon/fast

src/Dungeon.o: src/Dungeon.cpp.o
.PHONY : src/Dungeon.o

# target to build an object file
src/Dungeon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Dungeon.cpp.o
.PHONY : src/Dungeon.cpp.o

src/Dungeon.i: src/Dungeon.cpp.i
.PHONY : src/Dungeon.i

# target to preprocess a source file
src/Dungeon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Dungeon.cpp.i
.PHONY : src/Dungeon.cpp.i

src/Dungeon.s: src/Dungeon.cpp.s
.PHONY : src/Dungeon.s

# target to generate assembly for a file
src/Dungeon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Dungeon.cpp.s
.PHONY : src/Dungeon.cpp.s

src/Monster.o: src/Monster.cpp.o
.PHONY : src/Monster.o

# target to build an object file
src/Monster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Monster.cpp.o
.PHONY : src/Monster.cpp.o

src/Monster.i: src/Monster.cpp.i
.PHONY : src/Monster.i

# target to preprocess a source file
src/Monster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Monster.cpp.i
.PHONY : src/Monster.cpp.i

src/Monster.s: src/Monster.cpp.s
.PHONY : src/Monster.s

# target to generate assembly for a file
src/Monster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Monster.cpp.s
.PHONY : src/Monster.cpp.s

src/Path.o: src/Path.cpp.o
.PHONY : src/Path.o

# target to build an object file
src/Path.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Path.cpp.o
.PHONY : src/Path.cpp.o

src/Path.i: src/Path.cpp.i
.PHONY : src/Path.i

# target to preprocess a source file
src/Path.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Path.cpp.i
.PHONY : src/Path.cpp.i

src/Path.s: src/Path.cpp.s
.PHONY : src/Path.s

# target to generate assembly for a file
src/Path.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Path.cpp.s
.PHONY : src/Path.cpp.s

src/TileFactory.o: src/TileFactory.cpp.o
.PHONY : src/TileFactory.o

# target to build an object file
src/TileFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/TileFactory.cpp.o
.PHONY : src/TileFactory.cpp.o

src/TileFactory.i: src/TileFactory.cpp.i
.PHONY : src/TileFactory.i

# target to preprocess a source file
src/TileFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/TileFactory.cpp.i
.PHONY : src/TileFactory.cpp.i

src/TileFactory.s: src/TileFactory.cpp.s
.PHONY : src/TileFactory.s

# target to generate assembly for a file
src/TileFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/TileFactory.cpp.s
.PHONY : src/TileFactory.cpp.s

src/Trap.o: src/Trap.cpp.o
.PHONY : src/Trap.o

# target to build an object file
src/Trap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Trap.cpp.o
.PHONY : src/Trap.cpp.o

src/Trap.i: src/Trap.cpp.i
.PHONY : src/Trap.i

# target to preprocess a source file
src/Trap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Trap.cpp.i
.PHONY : src/Trap.cpp.i

src/Trap.s: src/Trap.cpp.s
.PHONY : src/Trap.s

# target to generate assembly for a file
src/Trap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Trap.cpp.s
.PHONY : src/Trap.cpp.s

src/Treasure.o: src/Treasure.cpp.o
.PHONY : src/Treasure.o

# target to build an object file
src/Treasure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Treasure.cpp.o
.PHONY : src/Treasure.cpp.o

src/Treasure.i: src/Treasure.cpp.i
.PHONY : src/Treasure.i

# target to preprocess a source file
src/Treasure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Treasure.cpp.i
.PHONY : src/Treasure.cpp.i

src/Treasure.s: src/Treasure.cpp.s
.PHONY : src/Treasure.s

# target to generate assembly for a file
src/Treasure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Treasure.cpp.s
.PHONY : src/Treasure.cpp.s

src/Wall.o: src/Wall.cpp.o
.PHONY : src/Wall.o

# target to build an object file
src/Wall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Wall.cpp.o
.PHONY : src/Wall.cpp.o

src/Wall.i: src/Wall.cpp.i
.PHONY : src/Wall.i

# target to preprocess a source file
src/Wall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Wall.cpp.i
.PHONY : src/Wall.cpp.i

src/Wall.s: src/Wall.cpp.s
.PHONY : src/Wall.s

# target to generate assembly for a file
src/Wall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/Wall.cpp.s
.PHONY : src/Wall.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Dungeon"
	@echo "... src/Dungeon.o"
	@echo "... src/Dungeon.i"
	@echo "... src/Dungeon.s"
	@echo "... src/Monster.o"
	@echo "... src/Monster.i"
	@echo "... src/Monster.s"
	@echo "... src/Path.o"
	@echo "... src/Path.i"
	@echo "... src/Path.s"
	@echo "... src/TileFactory.o"
	@echo "... src/TileFactory.i"
	@echo "... src/TileFactory.s"
	@echo "... src/Trap.o"
	@echo "... src/Trap.i"
	@echo "... src/Trap.s"
	@echo "... src/Treasure.o"
	@echo "... src/Treasure.i"
	@echo "... src/Treasure.s"
	@echo "... src/Wall.o"
	@echo "... src/Wall.i"
	@echo "... src/Wall.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/elyass/Dungeon/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

